# This file can be used to customize tox tests as well as other test frameworks like flake8 and mypy

[tox]
requires =
    tox>=4.51

[testenv]
description = run tests on Python {py_dot_ver}
base_python_file = .python-version
deps =
    pytest
commands =
    pytest {posargs}
